### ISSUE TITLE
[feature-request] list the reviewers in the sumamry

### ISSUE THREAD

**Issue by Minipada** [ohbarye/review-waiting-list-bot#53]
Hello,
Thanks for the app, I could make it run pretty fast. One feature I would really like is to know who has to review in the summary. Working in a team of 5 people, I wouldn't like to click on each pull request to know if I have to review it.

I'm not a js adept but I don't see anywhere that you fetch the review list, is it something possible?

Thanks!

**Comment by ohbarye** [comment]
Hello @Minipada , thanks for your feedback.

> One feature I would really like is to know who has to review in the summary.

Let me elaborate on your suggestion, what you want to have in the pull request list on Slack is requested reviewer names on the rightmost in a pull request page? (emphasized by the pink frame)

![image](https://user-images.githubusercontent.com/1811616/43585835-0839c95a-96a1-11e8-9097-a5906219e51e.png)

How the names appear on Slack (just an idea):

```
:memo: Review waiting list!
1. `Add awesome feature` https://github.com/ohbarye/review-waiting-list-bot/pull/1000 by Minipada
  (requested reviewers: ohbarye, foo, bar)
That's all. Please review!
```

**Comment by Minipada** [comment]
Hey, yes,
There's a fork where someone actually did it. I guess he could do some pull request here.
https://github.com/jamdrop/review-waiting-list-bot/commit/837235958f9e7df548239e883051ab1c0d87779c

**Comment by ohbarye** [comment]
@Minipada 
I finished implementation of this feature, please check out the latest one.

@jamdrop
I referred your preceding implementation and idea. Thanks.
