### ISSUE TITLE
bot offline after a few days of idling

### ISSUE THREAD

**Issue by gionn** [ohbarye/review-waiting-list-bot#59]
Every monday I find the bot offline on our slack after the weekend idling, a container restart fixes it, in the logs I have:

```
notice: RTM close event: 1006 : 
error: Abnormal websocket close event, attempting to reconnect
notice: ** BOT ID: pierino ...reconnect attempt #1 of null being made after 1000ms
notice: ** BOT ID: pierino ...attempting to connect to RTM!
notice: RTM websocket opened
error: Error: Stale RTM connection, closing RTM
```

Thanks.

**Comment by ohbarye** [comment]
Thanks for the report.
Hmm, I've never seen the error for my own bot on heroku. 🤔

**Comment by gionn** [comment]
Maybe enabling retry in botkit is worth a try?

https://botkit.ai/docs/readme-slack.html#botkitslackbot

**Comment by gionn** [comment]
Just to make clear that this is not just a sporadic issue, I had to restart the container also on this monday :smile:

**Comment by Petemir** [comment]
Hello,

I also have this problem, but apparently the [retry option in botkit isn't (wasn't?) working properly](https://github.com/howdyai/botkit/issues/261), maybe [this](https://github.com/howdyai/botkit/issues/261#issuecomment-258954201) could be a solution.

**Comment by ohbarye** [comment]
@gionn @Petemir 
Thanks for the info and sorry for my late response.

Well, I'm still not able to reproduce this problem on my end. So if you'd like to resolve this issue, could you fork this repo and try the approach suggested by @Petemir or anything?

Once you confirm that that's the solution, please send a pull request to the repo. Then I will perhaps merge the patch after review.
